import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib";
import { Providers } from "@/components";
import "./globals.css";

export const fontInter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
})

export const metadata: Metadata = {
  title: "Tiny Target",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <head>
        <link rel="icon" href="/tiny-target-logo.ico"></link>
      </head>
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
        fontInter.variable
      )}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}